// @ts-nocheck
/**
 * BillForge Email Notification Service
 * Integrates SMTP credentials & templates for Client Onboarding, Password Resets, and Bill Invoices.
 */

export const SMTP_CONFIG = {
  host: 'smtp.gmail.com',
  port: 465,
  service: 'gmail',
  user: 'rightsight365@gmail.com',
  pass: 'ktgvoitoxfhijqmr',
  toMeEmail: 'sarangan365@gmail.com',
  toMeMobile: '1234567890',
};

/**
 * Send Onboarding Welcome / Approval Email
 */
export async function sendOnboardingEmail({
  toEmail,
  ownerName,
  quarryName,
  status,
}: {
  toEmail: string;
  ownerName: string;
  quarryName: string;
  status: string;
}) {
  const targetEmail = toEmail || SMTP_CONFIG.toMeEmail;
  console.log(`[EmailService] Dispatching Onboarding Email via SMTP to ${targetEmail} (${quarryName})`);

  const isApproved = status === 'active';
  const subject = isApproved
    ? `Welcome to BillForge! Your Quarry Portal for ${quarryName} is Activated 🎉`
    : `Registration Received - Pending Approval for ${quarryName} ⏳`;

  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; background-color: #ffffff;">
      <div style="background-color: #0F2050; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: bold;">BillForge Quarry Operations</h1>
        <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 13px;">Supply Chain & Billing Platform</p>
      </div>
      
      <h2 style="color: #0F2050; font-size: 18px; margin-top: 0;">Hello ${ownerName || 'Quarry Partner'},</h2>
      
      <p style="font-size: 15px; color: #334155; line-height: 1.6;">
        ${isApproved
          ? `Great news! Your quarry business <strong>${quarryName}</strong> has been officially approved and activated by the system administrator. You can now sign in to manage bills, materials, drivers, and ledger dues.`
          : `Thank you for registering <strong>${quarryName}</strong> with BillForge. Your registration has been submitted and is currently pending review by our administrator.`}
      </p>
      
      <div style="background-color: #f8fafc; padding: 16px; border-radius: 8px; margin: 20px 0; border-left: 4px solid ${isApproved ? '#16a34a' : '#d97706'};">
        <p style="margin: 0; font-weight: bold; color: #0f172a; font-size: 14px;">Business Name: ${quarryName}</p>
        <p style="margin: 6px 0 0 0; color: #475569; font-size: 13px;">Account Status: <span style="font-weight: bold; color: ${isApproved ? '#16a34a' : '#d97706'};">${status.toUpperCase()}</span></p>
        <p style="margin: 4px 0 0 0; color: #475569; font-size: 13px;">Contact Email: ${targetEmail}</p>
      </div>

      <p style="font-size: 13px; color: #64748b; line-height: 1.5; margin-top: 24px;">
        Need assistance? Contact support at <a href="mailto:${SMTP_CONFIG.toMeEmail}" style="color: #2563eb;">${SMTP_CONFIG.toMeEmail}</a> or call ${SMTP_CONFIG.toMeMobile}.
      </p>
    </div>
  `;

  return dispatchEmail({ to: targetEmail, subject, html: htmlBody });
}

/**
 * Send Temporary Password Reset Email
 */
export async function sendPasswordResetEmail({
  toEmail,
  ownerName,
  quarryName,
  tempPassword,
}: {
  toEmail: string;
  ownerName: string;
  quarryName: string;
  tempPassword: string;
}) {
  const targetEmail = toEmail || SMTP_CONFIG.toMeEmail;
  console.log(`[EmailService] Dispatching Temp Password Reset Email via SMTP to ${targetEmail}`);

  const subject = `BillForge - Temporary Unlock Password for ${quarryName}`;
  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; background-color: #ffffff;">
      <div style="background-color: #0F2050; padding: 16px; border-radius: 8px; text-align: center; margin-bottom: 20px;">
        <h1 style="color: #ffffff; margin: 0; font-size: 22px;">BillForge Security</h1>
      </div>

      <h2 style="color: #0F2050; font-size: 18px; margin-top: 0;">Password Reset Notification</h2>
      <p style="font-size: 15px; color: #334155;">Hello ${ownerName || 'Quarry Owner'},</p>
      <p style="font-size: 15px; color: #334155;">Your temporary unlock password for <strong>${quarryName}</strong> has been generated by the administrator:</p>
      
      <div style="background-color: #EBF5FB; border: 1px border #BAE6FD; padding: 18px; border-radius: 10px; text-align: center; margin: 20px 0;">
        <span style="font-size: 26px; font-weight: bold; color: #0F2050; letter-spacing: 3px;">${tempPassword}</span>
      </div>

      <p style="font-size: 13px; color: #64748b; line-height: 1.5;">
        Please use this temporary password to log in at your portal. You can update your password anytime after logging in.
      </p>
    </div>
  `;

  return dispatchEmail({ to: targetEmail, subject, html: htmlBody });
}

/**
 * Send Bill / Invoice Email to Customer
 */
export async function sendBillInvoiceEmail({
  toEmail,
  customerName,
  billNumber,
  totalAmount,
  quarryName,
}: {
  toEmail: string;
  customerName: string;
  billNumber: string;
  totalAmount: number;
  quarryName: string;
}) {
  const targetEmail = toEmail || SMTP_CONFIG.toMeEmail;
  console.log(`[EmailService] Dispatching Bill Invoice Email via SMTP to ${targetEmail}`);

  const subject = `Invoice #${billNumber} from ${quarryName}`;
  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; background-color: #ffffff;">
      <h2 style="color: #0F2050; margin-top: 0;">Tax Invoice / Bill #${billNumber}</h2>
      <p style="font-size: 15px; color: #334155;">Dear ${customerName || 'Valued Customer'},</p>
      <p style="font-size: 15px; color: #334155;">Thank you for your order with <strong>${quarryName}</strong>. Below is your invoice summary:</p>
      
      <div style="background-color: #f8fafc; padding: 18px; border-radius: 10px; margin: 20px 0; border: 1px solid #e2e8f0;">
        <p style="margin: 4px 0; font-size: 14px; color: #334155;"><strong>Bill Number:</strong> #${billNumber}</p>
        <p style="margin: 4px 0; font-size: 14px; color: #334155;"><strong>Issued By:</strong> ${quarryName}</p>
        <p style="margin: 10px 0 0 0; font-size: 18px; font-weight: bold; color: #16a34a;"><strong>Total Amount:</strong> ₹ ${totalAmount.toLocaleString('en-IN')}</p>
      </div>

      <p style="font-size: 13px; color: #64748b;">
        If you have questions regarding this bill, please contact ${quarryName}.
      </p>
    </div>
  `;

  return dispatchEmail({ to: targetEmail, subject, html: htmlBody });
}

export function getSMTPConfig() {
  if (typeof localStorage !== 'undefined') {
    try {
      const saved = localStorage.getItem('bf_admin_smtp_config');
      if (saved) {
        return { ...SMTP_CONFIG, ...JSON.parse(saved) };
      }
    } catch {}
  }
  return SMTP_CONFIG;
}

export function saveSMTPConfig(config: any) {
  if (typeof localStorage !== 'undefined') {
    try {
      localStorage.setItem('bf_admin_smtp_config', JSON.stringify(config));
    } catch {}
  }
}

/**
 * Core Serverless SMTP Dispatcher
 */
async function dispatchEmail({ to, subject, html }: { to: string; subject: string; html: string }) {
  try {
    const getApiBase = () => {
      if (typeof window !== 'undefined' && window.location && window.location.origin) {
        return window.location.origin;
      }
      return 'https://billforge-lovat.vercel.app';
    };

    const currentSmtp = getSMTPConfig();
    const apiUrl = `${getApiBase()}/api/email`;
    console.log(`[EmailService] Posting email request via Serverless API to ${to}...`);

    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ to, subject, html, smtpConfig: currentSmtp }),
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Server HTTP ${response.status}: ${errText}`);
    }

    const data = await response.json();
    console.log('[EmailService] SMTP Dispatch Successful:', data);
    return data;
  } catch (error) {
    console.error('[SMTP Mailer Error]:', error.message || error);
    return { success: false, error: error.message || String(error) };
  }
}


