// @ts-nocheck
/**
 * BillForge Dynamic Email Template Engine
 * Manages modular .ejs email templates from mailTemplates/ directory
 */

const ONBOARDING_EJS = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Welcome to BillForge Platform</title></head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05); border: 1px solid #e2e8f0;">
    <div style="background: linear-gradient(135deg, #0F2050 0%, #1E3A8A 100%); padding: 32px 24px; text-align: center; color: #ffffff;">
      <h1 style="margin: 0; font-size: 26px; font-weight: 800; letter-spacing: 0.5px;">BillForge</h1>
      <p style="margin: 6px 0 0 0; font-size: 13px; color: #93c5fd; text-transform: uppercase; letter-spacing: 1px;">Quarry Operations Platform</p>
    </div>
    <div style="padding: 32px 28px;">
      <h2 style="color: #0F2050; font-size: 20px; margin-top: 0;">Welcome, <%= ownerName %>! 🎉</h2>
      <p style="font-size: 15px; color: #334155; line-height: 1.6;">
        Your business registration for <strong><%= quarryName %></strong> has been reviewed and approved!
      </p>
      <div style="background-color: #f0fdf4; border: 1.5px solid #bbf7d0; border-radius: 12px; padding: 20px; margin: 24px 0;">
        <div style="font-size: 14px; font-weight: 700; color: #166534; margin-bottom: 8px;">Business Status: <%= status.toUpperCase() %></div>
        <p style="margin: 0; font-size: 13px; color: #15803d; line-height: 1.5;">
          You can now generate automated tax bills, dispatch lorry consignments, track real-time fleet delivery, and manage customer credit balances.
        </p>
      </div>
      <div style="text-align: center; margin-top: 28px;">
        <a href="https://billforge-lovat.vercel.app/quarry-owner-portal" style="background-color: #E65100; color: #ffffff; padding: 14px 28px; text-decoration: none; font-size: 15px; font-weight: 700; border-radius: 10px; display: inline-block;">Access Owner Portal 🚀</a>
      </div>
    </div>
    <div style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b;">
      <p style="margin: 0;">Need developer support? Contact <strong>+91 9894698049</strong></p>
      <p style="margin: 4px 0 0 0; color: #94a3b8;">© 2026 BillForge Platform. All rights reserved.</p>
    </div>
  </div>
</body>
</html>`;

const PASSWORD_RESET_EJS = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Temporary Passcode Reset - BillForge</title></head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05); border: 1px solid #e2e8f0;">
    <div style="background: linear-gradient(135deg, #0F2050 0%, #1E3A8A 100%); padding: 32px 24px; text-align: center; color: #ffffff;">
      <h1 style="margin: 0; font-size: 26px; font-weight: 800; letter-spacing: 0.5px;">BillForge</h1>
      <p style="margin: 6px 0 0 0; font-size: 13px; color: #93c5fd; text-transform: uppercase; letter-spacing: 1px;">Security & Account Protection</p>
    </div>
    <div style="padding: 32px 28px;">
      <h2 style="color: #0F2050; font-size: 20px; margin-top: 0;">Password Reset Request</h2>
      <p style="font-size: 15px; color: #334155; line-height: 1.6;">
        Dear <strong><%= ownerName %></strong> (<%= quarryName %>),
      </p>
      <p style="font-size: 14px; color: #475569; line-height: 1.5;">
        A temporary login passcode was generated by the System Administrator to unlock your portal account.
      </p>
      <div style="background-color: #fff3e0; border: 2px dashed #ffe0b2; border-radius: 14px; padding: 24px; text-align: center; margin: 24px 0;">
        <div style="font-size: 12px; font-weight: 700; color: #c2410c; text-transform: uppercase; letter-spacing: 1px;">Temporary Unlock Passcode</div>
        <div style="font-size: 32px; font-weight: 900; color: #e65100; letter-spacing: 4px; margin: 10px 0;"><%= tempPassword %></div>
        <div style="font-size: 12px; color: #d97706;">Valid for 1-time login. Please change your password after logging in.</div>
      </div>
      <p style="font-size: 13px; color: #64748b; line-height: 1.5;">
        If you did not request a password reset, please contact Developer Support immediately at <strong>+91 9894698049</strong>.
      </p>
    </div>
    <div style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b;">
      <p style="margin: 0;">BillForge Platform Admin Support Hotline: <strong>+91 9894698049</strong></p>
      <p style="margin: 4px 0 0 0; color: #94a3b8;">© 2026 BillForge Platform. All rights reserved.</p>
    </div>
  </div>
</body>
</html>`;

const BILL_INVOICE_EJS = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Tax Invoice - BillForge</title></head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05); border: 1px solid #e2e8f0;">
    <div style="background: linear-gradient(135deg, #0F2050 0%, #1E3A8A 100%); padding: 32px 24px; text-align: center; color: #ffffff;">
      <h1 style="margin: 0; font-size: 26px; font-weight: 800; letter-spacing: 0.5px;"><%= quarryName %></h1>
      <p style="margin: 6px 0 0 0; font-size: 13px; color: #93c5fd; text-transform: uppercase; letter-spacing: 1px;">Official Tax Invoice & Bill</p>
    </div>
    <div style="padding: 32px 28px;">
      <h2 style="color: #0F2050; font-size: 20px; margin-top: 0;">Invoice #<%= billNumber %></h2>
      <p style="font-size: 15px; color: #334155;">Dear <strong><%= customerName %></strong>,</p>
      <p style="font-size: 14px; color: #475569; line-height: 1.5;">
        Thank you for your order with <strong><%= quarryName %></strong>. Below is your official bill summary:
      </p>
      <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 6px 0; font-size: 14px; color: #64748b;">Bill Number:</td>
            <td style="padding: 6px 0; font-size: 14px; font-weight: 700; color: #0F2050; text-align: right;">#<%= billNumber %></td>
          </tr>
          <tr>
            <td style="padding: 6px 0; font-size: 14px; color: #64748b;">Issued By:</td>
            <td style="padding: 6px 0; font-size: 14px; font-weight: 700; color: #0F2050; text-align: right;"><%= quarryName %></td>
          </tr>
          <tr style="border-top: 1px solid #cbd5e1;">
            <td style="padding: 12px 0 6px 0; font-size: 16px; font-weight: 800; color: #0F2050;">Total Amount:</td>
            <td style="padding: 12px 0 6px 0; font-size: 20px; font-weight: 900; color: #16a34a; text-align: right;">₹ <%= totalAmount %></td>
          </tr>
        </table>
      </div>
      <p style="font-size: 13px; color: #64748b; line-height: 1.5;">
        If you have any questions regarding this invoice, please contact <strong><%= quarryName %></strong>.
      </p>
    </div>
    <div style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b;">
      <p style="margin: 0;">Automated Billing by BillForge Platform</p>
      <p style="margin: 4px 0 0 0; color: #94a3b8;">© 2026 <%= quarryName %>. All rights reserved.</p>
    </div>
  </div>
</body>
</html>`;

export const TEMPLATES = {
  onboarding: ONBOARDING_EJS,
  passwordReset: PASSWORD_RESET_EJS,
  billInvoice: BILL_INVOICE_EJS,
};

/**
 * Render EJS/HTML string by replacing <%= varName %> tags with context values
 */
export function renderTemplate(templateName: 'onboarding' | 'passwordReset' | 'billInvoice', context: Record<string, any>): string {
  const templateContent = TEMPLATES[templateName];
  if (!templateContent) {
    throw new Error(`Template "${templateName}" not found.`);
  }

  let rendered = String(templateContent);
  Object.keys(context).forEach((key) => {
    const regex = new RegExp(`<%=\\s*${key}\\s*%>`, 'g');
    const val = context[key] !== undefined && context[key] !== null ? context[key] : '';
    rendered = rendered.replace(regex, val);
  });

  return rendered;
}

