// @ts-nocheck
import React, { useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  TextInput, Switch, Alert, Linking, Platform, ActivityIndicator,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { Colors, Typography, Spacing, BorderRadius } from '../src/theme';
import { useAuth } from '../src/context/AuthContext';
import { useToast } from '../src/context/ToastContext';
import {
  getWhatsAppStatus,
  requestBaileysPairingCode,
  disconnectWhatsAppSession,
  sendDirectWhatsAppMessage,
  generateWhatsAppDocumentShareUrl,
} from '../src/services/whatsappService';

const WA_SETTINGS_KEY = 'bf_wa_settings';

function webGet(key) { try { const v = localStorage.getItem(key); return v ? JSON.parse(v) : null; } catch { return null; } }
function webSet(key, val) { try { localStorage.setItem(key, JSON.stringify(val)); } catch {} }

const TEMPLATE_PRESETS = [
  { id: 'invoice', label: 'Invoice Notification', template: 'Dear {customer_name}, your invoice #{bill_number} for Rs. {amount} has been generated by {company_name}. Thank you for your business!' },
  { id: 'payment', label: 'Payment Confirmation', template: 'Hi {customer_name}, we have received your payment of Rs. {amount} against bill #{bill_number}. Thank you!' },
  { id: 'reminder', label: 'Payment Reminder', template: 'Dear {customer_name}, this is a reminder that payment of Rs. {amount} is due for bill #{bill_number}. - {company_name}' },
];

export default function WhatsAppSettingsScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { quarryId, user } = useAuth();
  const { showToast } = useToast();
  const targetQid = quarryId || user?.quarry_id || 1;

  // Settings State
  const [waNum, setWaNum] = useState('');
  const [sharingMode, setSharingMode] = useState('direct_baileys'); // 'direct_baileys' | 'url_share' | 'custom_gateway'
  const [sendOnSave, setSendOnSave] = useState(true);
  const [sendOnReminder, setSendOnReminder] = useState(true);
  const [selectedTemplate, setSelectedTemplate] = useState('invoice');
  const [customTemplate, setCustomTemplate] = useState('');
  const [gatewayUrl, setGatewayUrl] = useState('');
  const [apiKey, setApiKey] = useState('');

  // Baileys Pairing State
  const [sessionStatus, setSessionStatus] = useState({ connected: false, status: 'disconnected', pairing_code: null });
  const [loadingStatus, setLoadingStatus] = useState(true);
  const [pairingLoading, setPairingLoading] = useState(false);
  const [pairingCode, setPairingCode] = useState('');
  const [testSending, setTestSending] = useState(false);

  useEffect(() => {
    loadLocalSettings();
    checkServerSession();
  }, [targetQid]);

  const loadLocalSettings = () => {
    const s = webGet(`${WA_SETTINGS_KEY}_${targetQid}`);
    if (s) {
      setWaNum(s.whatsapp_number || '');
      setSharingMode(s.sharing_mode || 'direct_baileys');
      setSendOnSave(s.send_on_save !== false);
      setSendOnReminder(s.send_on_reminder !== false);
      setSelectedTemplate(s.selected_template || 'invoice');
      setCustomTemplate(s.custom_template || '');
      setGatewayUrl(s.gateway_url || '');
      setApiKey(s.api_key || '');
    }
  };

  const checkServerSession = async () => {
    setLoadingStatus(true);
    try {
      const res = await getWhatsAppStatus(targetQid);
      if (res && res.success) {
        setSessionStatus(res);
        if (res.pairing_code) setPairingCode(res.pairing_code);
        if (res.phone && !waNum) setWaNum(res.phone.replace(/^91/, ''));
      }
    } catch (e) {
      console.warn('Error checking WhatsApp session:', e);
    } finally {
      setLoadingStatus(false);
    }
  };

  const handleGeneratePairingCode = async () => {
    const clean = waNum.replace(/\D/g, '');
    if (!clean || clean.length < 10) {
      Alert.alert('Phone Required', 'Please enter a valid 10-digit WhatsApp phone number to generate your pairing code.');
      return;
    }

    setPairingLoading(true);
    try {
      const res = await requestBaileysPairingCode(targetQid, clean);
      if (res && res.success) {
        setPairingCode(res.pairing_code);
        setSessionStatus(prev => ({ ...prev, status: 'paired', connected: true }));
        showToast(`Pairing code ${res.pairing_code} generated! 📱`, 'success', 'WhatsApp Linked');
        Alert.alert(
          'WhatsApp Pairing Code 📱',
          `Your 8-character pairing code is:\n\n👉  ${res.pairing_code}  👈\n\nHow to link on your phone:\n1. Open WhatsApp > Settings > Linked Devices\n2. Tap "Link a device" > "Link with phone number instead"\n3. Enter this 8-character code.`
        );
      } else {
        Alert.alert('Error', res?.error || 'Failed to generate pairing code.');
      }
    } catch (err) {
      Alert.alert('Error', 'Failed to connect to serverless WhatsApp gateway.');
    } finally {
      setPairingLoading(false);
    }
  };

  const handleDisconnect = async () => {
    try {
      await disconnectWhatsAppSession(targetQid);
      setSessionStatus({ connected: false, status: 'disconnected', pairing_code: null });
      setPairingCode('');
      showToast('WhatsApp session disconnected.', 'info', 'Disconnected');
    } catch (e) {
      Alert.alert('Error', 'Failed to disconnect session.');
    }
  };

  const handleSaveSettings = () => {
    webSet(`${WA_SETTINGS_KEY}_${targetQid}`, {
      whatsapp_number: waNum.trim(),
      sharing_mode: sharingMode,
      send_on_save: sendOnSave,
      send_on_reminder: sendOnReminder,
      selected_template: selectedTemplate,
      custom_template: customTemplate.trim(),
      gateway_url: gatewayUrl.trim(),
      api_key: apiKey.trim(),
    });
    showToast('WhatsApp settings saved & synced! ✨', 'success', 'Settings Saved');
    Alert.alert('Settings Saved ✅', 'Your WhatsApp configuration and sharing preferences are active.');
  };

  const handleTestSend = async () => {
    const clean = waNum.replace(/\D/g, '');
    if (!clean || clean.length < 10) {
      Alert.alert('Phone Required', 'Enter your 10-digit WhatsApp number to receive a test message.');
      return;
    }

    setTestSending(true);
    const testMsg = `🔔 *BillForge Test Notification*\nHello! Your WhatsApp integration is working successfully. Automatic invoice dispatch is ready!`;

    if (sharingMode === 'url_share') {
      const url = generateWhatsAppDocumentShareUrl(clean, testMsg);
      Linking.openURL(url).catch(() => Alert.alert('Error', 'Could not launch WhatsApp.'));
      setTestSending(false);
      return;
    }

    try {
      const res = await sendDirectWhatsAppMessage({
        quarryId: targetQid,
        to: clean,
        message: testMsg,
        billNumber: 'BF-TEST-01',
        totalAmount: 5000,
        customerName: 'Test Business',
      });

      if (res && res.success) {
        showToast('Test WhatsApp message delivered! 🚀', 'success', 'Delivered');
        Alert.alert('Success ✅', `Test message sent to +91 ${clean} via ${res.channel}. Check your WhatsApp!`);
      } else {
        Alert.alert('Notice', 'Direct delivery queued. You can also use URL-Based Document Share as an instant zero-config alternative.');
      }
    } catch (e) {
      Alert.alert('Error', 'Failed to send test message.');
    } finally {
      setTestSending(false);
    }
  };

  const isLinked = sessionStatus.status === 'paired' || sessionStatus.connected;

  return (
    <View style={[styles.root, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={22} color={Colors.text} />
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={styles.headerTitle}>WhatsApp Integration</Text>
          <Text style={styles.headerSub}>Serverless Baileys & Direct URL Document Sharing</Text>
        </View>
        <View style={[styles.statusBadge, isLinked ? styles.badgeSuccess : styles.badgeMuted]}>
          <Ionicons name={isLinked ? "shield-checkmark" : "logo-whatsapp"} size={14} color="#FFF" />
          <Text style={styles.statusBadgeText}>{isLinked ? "Baileys Linked" : "URL Ready"}</Text>
        </View>
      </View>

      <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 16 }}>
        {/* ─── 1. Sharing Mode Selector ─── */}
        <View style={styles.sectionCard}>
          <Text style={styles.sectionTitle}>Default Sharing Method</Text>
          <Text style={styles.sectionSub}>Choose how invoices and documents are dispatched to customers.</Text>

          <View style={styles.modesContainer}>
            {/* Mode 1: Baileys Direct Serverless */}
            <TouchableOpacity
              style={[styles.modeCard, sharingMode === 'direct_baileys' && styles.modeCardActive]}
              onPress={() => setSharingMode('direct_baileys')}
            >
              <View style={[styles.modeIconCircle, { backgroundColor: '#EEF2FF' }]}>
                <Ionicons name="flash-outline" size={20} color="#6366F1" />
              </View>
              <View style={{ flex: 1 }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                  <Text style={[styles.modeTitle, sharingMode === 'direct_baileys' && { color: Colors.primary }]}>Direct Serverless (Baileys)</Text>
                  <View style={styles.proTag}><Text style={styles.proTagText}>Recommended</Text></View>
                </View>
                <Text style={styles.modeDesc}>Sends invoice PDF & message automatically in background via linked phone session without opening apps.</Text>
              </View>
              <Ionicons
                name={sharingMode === 'direct_baileys' ? "radio-button-on" : "radio-button-off"}
                size={20}
                color={sharingMode === 'direct_baileys' ? Colors.primary : Colors.textTertiary}
              />
            </TouchableOpacity>

            {/* Mode 2: Instant URL Document Share */}
            <TouchableOpacity
              style={[styles.modeCard, sharingMode === 'url_share' && styles.modeCardActive]}
              onPress={() => setSharingMode('url_share')}
            >
              <View style={[styles.modeIconCircle, { backgroundColor: '#ECFDF5' }]}>
                <Ionicons name="globe-outline" size={20} color="#10B981" />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={[styles.modeTitle, sharingMode === 'url_share' && { color: Colors.success }]}>URL-Based Document Share</Text>
                <Text style={styles.modeDesc}>Opens WhatsApp Web or App with pre-filled invoice message and direct document preview link.</Text>
              </View>
              <Ionicons
                name={sharingMode === 'url_share' ? "radio-button-on" : "radio-button-off"}
                size={20}
                color={sharingMode === 'url_share' ? Colors.success : Colors.textTertiary}
              />
            </TouchableOpacity>

            {/* Mode 3: Custom API Gateway */}
            <TouchableOpacity
              style={[styles.modeCard, sharingMode === 'custom_gateway' && styles.modeCardActive]}
              onPress={() => setSharingMode('custom_gateway')}
            >
              <View style={[styles.modeIconCircle, { backgroundColor: '#FEF3C7' }]}>
                <Ionicons name="server-outline" size={20} color="#D97706" />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={[styles.modeTitle, sharingMode === 'custom_gateway' && { color: '#D97706' }]}>Custom Webhook / API Gateway</Text>
                <Text style={styles.modeDesc}>Route through your private WhatsApp gateway endpoint or WWebJS instance.</Text>
              </View>
              <Ionicons
                name={sharingMode === 'custom_gateway' ? "radio-button-on" : "radio-button-off"}
                size={20}
                color={sharingMode === 'custom_gateway' ? '#D97706' : Colors.textTertiary}
              />
            </TouchableOpacity>
          </View>
        </View>

        {/* ─── 2. Baileys Phone Linking & Pairing Code ─── */}
        <View style={styles.sectionCard}>
          <Text style={styles.sectionTitle}>Business Phone & Baileys Pairing</Text>
          <Text style={styles.sectionSub}>Enter your 10-digit WhatsApp number to link via an official 8-character pairing code.</Text>

          <View style={styles.phoneInputRow}>
            <View style={styles.countryCode}><Text style={styles.countryCodeText}>+91</Text></View>
            <TextInput
              style={styles.phoneInput}
              value={waNum}
              onChangeText={setWaNum}
              placeholder="9876543210"
              placeholderTextColor={Colors.textTertiary}
              keyboardType="phone-pad"
              maxLength={10}
            />
            <TouchableOpacity
              style={[styles.actionChipBtn, isLinked && { backgroundColor: Colors.dangerLight, borderColor: Colors.dangerBorder }]}
              onPress={isLinked ? handleDisconnect : handleGeneratePairingCode}
              disabled={pairingLoading}
            >
              {pairingLoading ? (
                <ActivityIndicator size="small" color={Colors.primary} />
              ) : (
                <>
                  <Ionicons name={isLinked ? "log-out-outline" : "key-outline"} size={14} color={isLinked ? Colors.danger : Colors.primary} />
                  <Text style={[styles.actionChipText, isLinked && { color: Colors.danger }]}>
                    {isLinked ? "Disconnect" : "Get Code"}
                  </Text>
                </>
              )}
            </TouchableOpacity>
          </View>

          {/* Pairing Code Card */}
          {pairingCode ? (
            <View style={styles.pairingCodeCard}>
              <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                  <Ionicons name="key" size={16} color="#4F46E5" />
                  <Text style={styles.pairingCodeLabel}>Baileys Pairing Code:</Text>
                </View>
                <View style={styles.badgeSuccess}><Text style={{ color: '#fff', fontSize: 10, fontWeight: '700' }}>Active</Text></View>
              </View>
              <Text style={styles.pairingCodeDisplay}>{pairingCode}</Text>
              <Text style={styles.pairingCodeInstructions}>
                1. Open WhatsApp on your phone{'\n'}
                2. Tap Settings &gt; Linked Devices &gt; "Link with phone number instead"{'\n'}
                3. Enter code above to authorize direct serverless sending!
              </Text>
            </View>
          ) : null}

          {/* Custom Gateway Input (If selected) */}
          {sharingMode === 'custom_gateway' && (
            <View style={{ marginTop: 14 }}>
              <Text style={styles.inputLabel}>Gateway Webhook URL</Text>
              <TextInput
                style={styles.textInput}
                value={gatewayUrl}
                onChangeText={setGatewayUrl}
                placeholder="https://your-whatsapp-gateway.com/send"
                placeholderTextColor={Colors.textTertiary}
              />
              <Text style={[styles.inputLabel, { marginTop: 10 }]}>API Authorization Key (Optional)</Text>
              <TextInput
                style={styles.textInput}
                value={apiKey}
                onChangeText={setApiKey}
                placeholder="Bearer token or API Secret"
                placeholderTextColor={Colors.textTertiary}
                secureTextEntry
              />
            </View>
          )}

          <TouchableOpacity style={styles.testBtn} onPress={handleTestSend} disabled={testSending}>
            {testSending ? (
              <ActivityIndicator size="small" color="#22C55E" />
            ) : (
              <>
                <Ionicons name="paper-plane-outline" size={16} color="#22C55E" />
                <Text style={styles.testBtnText}>Send Test WhatsApp Message</Text>
              </>
            )}
          </TouchableOpacity>
        </View>

        {/* ─── 3. Automation Toggles ─── */}
        <View style={styles.sectionCard}>
          <Text style={styles.sectionTitle}>Automation Preferences</Text>
          <View style={styles.settingRow}>
            <View style={{ flex: 1, paddingRight: 10 }}>
              <Text style={styles.settingLabel}>Send Automatically on Bill Save</Text>
              <Text style={styles.settingDesc}>Dispatch invoice summary and link as soon as a new bill is created.</Text>
            </View>
            <Switch value={sendOnSave} onValueChange={setSendOnSave} trackColor={{ false: Colors.border, true: Colors.primary }} thumbColor="#FFF" />
          </View>
          <View style={styles.divider} />
          <View style={styles.settingRow}>
            <View style={{ flex: 1, paddingRight: 10 }}>
              <Text style={styles.settingLabel}>Payment Reminder Alerts</Text>
              <Text style={styles.settingDesc}>Allow sending 1-click balance reminders from ledger and history.</Text>
            </View>
            <Switch value={sendOnReminder} onValueChange={setSendOnReminder} trackColor={{ false: Colors.border, true: Colors.primary }} thumbColor="#FFF" />
          </View>
        </View>

        {/* ─── 4. Message Templates ─── */}
        <View style={styles.sectionCard}>
          <Text style={styles.sectionTitle}>Invoice Message Template</Text>
          <Text style={styles.sectionSub}>Supported tags: {'{customer_name}'}, {'{bill_number}'}, {'{amount}'}, {'{company_name}'}</Text>

          {TEMPLATE_PRESETS.map(t => (
            <TouchableOpacity
              key={t.id}
              style={[styles.templateCard, selectedTemplate === t.id && styles.templateCardActive]}
              onPress={() => setSelectedTemplate(t.id)}
            >
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
                <Text style={[styles.templateTitle, selectedTemplate === t.id && { color: Colors.primary }]}>{t.label}</Text>
                {selectedTemplate === t.id && <Ionicons name="checkmark-circle" size={18} color={Colors.primary} />}
              </View>
              <Text style={styles.templatePreview} numberOfLines={2}>{t.template}</Text>
            </TouchableOpacity>
          ))}

          {/* Custom Template */}
          <View style={[styles.templateCard, selectedTemplate === 'custom' && styles.templateCardActive]}>
            <TouchableOpacity
              style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}
              onPress={() => setSelectedTemplate('custom')}
            >
              <Text style={[styles.templateTitle, selectedTemplate === 'custom' && { color: Colors.primary }]}>Custom Template</Text>
              {selectedTemplate === 'custom' && <Ionicons name="checkmark-circle" size={18} color={Colors.primary} />}
            </TouchableOpacity>
            <TextInput
              style={styles.customTemplateInput}
              value={customTemplate}
              onChangeText={setCustomTemplate}
              placeholder="Type custom invoice message format..."
              placeholderTextColor={Colors.textTertiary}
              multiline
              onFocus={() => setSelectedTemplate('custom')}
            />
          </View>
        </View>

        {/* Save Button */}
        <TouchableOpacity style={styles.saveBtn} onPress={handleSaveSettings}>
          <Ionicons name="save-outline" size={18} color="#FFF" />
          <Text style={styles.saveBtnText}>Save WhatsApp Configuration</Text>
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    backgroundColor: Colors.surface, paddingHorizontal: 16, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: Colors.borderLight,
  },
  backBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.background, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 17, fontWeight: '700', color: Colors.text },
  headerSub: { fontSize: 12, color: Colors.textTertiary },
  statusBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  badgeSuccess: { backgroundColor: '#10B981' },
  badgeMuted: { backgroundColor: '#64748B' },
  statusBadgeText: { color: '#FFF', fontSize: 11, fontWeight: '700' },

  sectionCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16, padding: 16, marginBottom: 16,
    borderWidth: 1, borderColor: Colors.borderLight,
  },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: Colors.text, marginBottom: 4 },
  sectionSub: { fontSize: 12, color: Colors.textTertiary, marginBottom: 14, lineHeight: 18 },

  modesContainer: { gap: 10 },
  modeCard: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 14, padding: 14,
    borderWidth: 1.5, borderColor: Colors.border,
  },
  modeCardActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primarySurface,
  },
  modeIconCircle: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  modeTitle: { fontSize: 14, fontWeight: '700', color: Colors.text },
  modeDesc: { fontSize: 11, color: Colors.textSecondary, marginTop: 2, lineHeight: 16 },
  proTag: { backgroundColor: '#EEF2FF', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  proTagText: { color: '#4F46E5', fontSize: 10, fontWeight: '700' },

  phoneInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  countryCode: {
    backgroundColor: Colors.surfaceElevated, borderWidth: 1.5, borderColor: Colors.border,
    borderRadius: 12, paddingHorizontal: 12, paddingVertical: 13,
  },
  countryCodeText: { color: Colors.text, fontWeight: '700', fontSize: 14 },
  phoneInput: {
    flex: 1, backgroundColor: Colors.surfaceElevated, borderWidth: 1.5, borderColor: Colors.border,
    borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12,
    fontSize: 15, color: Colors.text,
  },
  actionChipBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: Colors.primarySurface, borderWidth: 1.5, borderColor: Colors.primaryBorder,
    borderRadius: 12, paddingHorizontal: 12, paddingVertical: 13,
  },
  actionChipText: { color: Colors.primary, fontSize: 12, fontWeight: '700' },

  pairingCodeCard: {
    marginTop: 14, backgroundColor: '#EEF2FF',
    borderRadius: 14, padding: 16, borderWidth: 1.5, borderColor: '#C7D2FE',
  },
  pairingCodeLabel: { fontSize: 13, fontWeight: '700', color: '#312E81' },
  pairingCodeDisplay: { fontSize: 26, fontWeight: '900', color: '#4338CA', letterSpacing: 4, marginVertical: 8, textAlign: 'center' },
  pairingCodeInstructions: { fontSize: 11, color: '#3730A3', lineHeight: 16 },

  inputLabel: { fontSize: 12, fontWeight: '600', color: Colors.textSecondary, marginBottom: 4 },
  textInput: {
    backgroundColor: Colors.surfaceElevated, borderWidth: 1.5, borderColor: Colors.border,
    borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10,
    fontSize: 14, color: Colors.text,
  },

  testBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    marginTop: 14, paddingVertical: 12, borderRadius: 12,
    backgroundColor: Colors.successLight, borderWidth: 1.5, borderColor: Colors.successBorder,
  },
  testBtnText: { color: Colors.success, fontSize: 13, fontWeight: '700' },

  settingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10 },
  settingLabel: { fontSize: 14, fontWeight: '600', color: Colors.text },
  settingDesc: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  divider: { height: 1, backgroundColor: Colors.divider, marginVertical: 4 },

  templateCard: {
    backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 12,
    padding: 12, marginBottom: 10, borderWidth: 1.5, borderColor: Colors.border,
  },
  templateCardActive: { borderColor: Colors.primary, backgroundColor: Colors.primarySurface },
  templateTitle: { fontSize: 13, fontWeight: '700', color: Colors.text },
  templatePreview: { fontSize: 11, color: Colors.textSecondary, marginTop: 4, lineHeight: 16 },
  customTemplateInput: {
    backgroundColor: Colors.surfaceElevated, borderRadius: 8,
    padding: 10, fontSize: 13, color: Colors.text, minHeight: 60,
    borderWidth: 1, borderColor: Colors.border, marginTop: 4,
  },

  saveBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    backgroundColor: Colors.primary, paddingVertical: 16, borderRadius: 16,
    marginTop: 8,
  },
  saveBtnText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
});
