// @ts-nocheck
import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, TextInput, Switch, Alert, Linking, Platform } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../src/context/AuthContext';

const WA_SETTINGS_KEY = 'bf_wa_settings';

function webGet(key) { try { const v = localStorage.getItem(key); return v ? JSON.parse(v) : null; } catch { return null; } }
function webSet(key, val) { try { localStorage.setItem(key, JSON.stringify(val)); } catch {} }

const TEMPLATE_PRESETS = [
  { id: 'invoice', label: 'Invoice Notification', template: 'Dear {customer_name}, your invoice #{bill_number} for Rs. {amount} has been generated by {company_name}. Thank you for your business!' },
  { id: 'payment', label: 'Payment Confirmation', template: 'Hi {customer_name}, we have received your payment of Rs. {amount} against bill #{bill_number}. Your balance is Rs. {balance}. Thank you!' },
  { id: 'reminder', label: 'Payment Reminder', template: 'Dear {customer_name}, this is a reminder that your payment of Rs. {amount} is due for bill #{bill_number}. Please settle at your earliest. - {company_name}' },
  { id: 'delivery', label: 'Delivery Confirmation', template: 'Hello {customer_name}, your order of {material} ({quantity} {unit}) has been delivered. Please confirm receipt. - {company_name}' },
];

export default function WhatsAppSettingsScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { quarryId } = useAuth();
  const [waNum, setWaNum] = useState('');
  const [apiKey, setApiKey] = useState('');
  const [sendOnSave, setSendOnSave] = useState(true);
  const [sendOnReminder, setSendOnReminder] = useState(true);
  const [selectedTemplate, setSelectedTemplate] = useState('invoice');
  const [customTemplate, setCustomTemplate] = useState('');
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    if (Platform.OS === 'web') {
      const s = webGet(WA_SETTINGS_KEY + '_' + (quarryId || 1));
      if (s) {
        setWaNum(s.whatsapp_number || '');
        setApiKey(s.api_key || '');
        setSendOnSave(s.send_on_save !== false);
        setSendOnReminder(s.send_on_reminder !== false);
        setSelectedTemplate(s.selected_template || 'invoice');
        setCustomTemplate(s.custom_template || '');
      }
    }
  }, [quarryId]);

  const handleSave = () => {
    if (Platform.OS === 'web') {
      webSet(WA_SETTINGS_KEY + '_' + (quarryId || 1), {
        whatsapp_number: waNum.trim(),
        api_key: apiKey.trim(),
        send_on_save: sendOnSave,
        send_on_reminder: sendOnReminder,
        selected_template: selectedTemplate,
        custom_template: customTemplate.trim(),
      });
    }
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
    Alert.alert('Saved', 'WhatsApp settings have been saved.');
  };

  const testWhatsApp = () => {
    const phone = waNum.replace(/\D/g, '');
    if (!phone || phone.length < 10) { Alert.alert('Error', 'Please enter a valid WhatsApp number first.'); return; }
    const num = phone.length === 10 ? '91' + phone : phone;
    const url = Platform.OS === 'web'
      ? 'https://wa.me/' + num + '?text=Hello+from+BillForge+App!+This+is+a+test+message.'
      : 'whatsapp://send?phone=' + num + '&text=Hello+from+BillForge!';
    Linking.openURL(url).catch(() => Alert.alert('Error', 'Could not open WhatsApp. Please install WhatsApp.'));
  };

  const selectedPreset = TEMPLATE_PRESETS.find(t => t.id === selectedTemplate);

  return (
    <View style={[styles.root, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={{ padding: 4 }}>
          <Ionicons name="arrow-back" size={22} color="#1A1F2C" />
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={styles.headerTitle}>WhatsApp Settings</Text>
          <Text style={styles.headerSub}>Configure automatic WhatsApp notifications</Text>
        </View>
        <View style={[styles.waBadge, saved && { backgroundColor: '#22C55E' }]}>
          <Ionicons name={saved ? 'checkmark-circle' : 'logo-whatsapp'} size={16} color="#FFF" />
          <Text style={styles.waBadgeText}>{saved ? 'Saved!' : 'WhatsApp'}</Text>
        </View>
      </View>

      <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 16 }}>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Business WhatsApp Number</Text>
          <Text style={styles.sectionSub}>Your WhatsApp Business number that sends automatic notifications to customers.</Text>
          <View style={styles.inputRow}>
            <View style={styles.countryCode}><Text style={styles.countryCodeText}>+91</Text></View>
            <TextInput
              style={styles.inputField}
              value={waNum} onChangeText={setWaNum}
              placeholder="9876543210" placeholderTextColor="#9CA3AF"
              keyboardType="phone-pad" maxLength={10}
            />
            <TouchableOpacity style={styles.testBtn} onPress={testWhatsApp}>
              <Ionicons name="send-outline" size={14} color="#22C55E" />
              <Text style={styles.testBtnText}>Test</Text>
            </TouchableOpacity>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Auto-Send Notifications</Text>
          {[
            { label: 'Send on Bill Save', sub: 'Automatically send invoice link when a bill is saved', val: sendOnSave, set: setSendOnSave },
            { label: 'Send Payment Reminders', sub: 'Send reminder when payment due date approaches', val: sendOnReminder, set: setSendOnReminder },
          ].map(s => (
            <View key={s.label} style={styles.settingRow}>
              <View style={{ flex: 1 }}>
                <Text style={styles.settingLabel}>{s.label}</Text>
                <Text style={styles.settingDesc}>{s.sub}</Text>
              </View>
              <Switch value={s.val} onValueChange={s.set} trackColor={{ false: '#DDD', true: '#25D366' }} thumbColor="#FFF" />
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Message Templates</Text>
          <Text style={styles.sectionSub}>Select a template for automatic messages. Available variables: {'{customer_name}'}, {'{bill_number}'}, {'{amount}'}, {'{company_name}'}</Text>
          {TEMPLATE_PRESETS.map(t => (
            <TouchableOpacity
              key={t.id}
              style={[styles.templateCard, selectedTemplate === t.id && styles.templateCardActive]}
              onPress={() => setSelectedTemplate(t.id)}
            >
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
                <Text style={[styles.templateTitle, selectedTemplate === t.id && { color: '#25D366' }]}>{t.label}</Text>
                {selectedTemplate === t.id && <Ionicons name="checkmark-circle" size={18} color="#25D366" />}
              </View>
              <Text style={styles.templatePreview} numberOfLines={2}>{t.template}</Text>
            </TouchableOpacity>
          ))}
          <View style={[styles.templateCard, selectedTemplate === 'custom' && styles.templateCardActive]}>
            <TouchableOpacity
              style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}
              onPress={() => setSelectedTemplate('custom')}
            >
              <Text style={[styles.templateTitle, selectedTemplate === 'custom' && { color: '#25D366' }]}>Custom Template</Text>
              {selectedTemplate === 'custom' && <Ionicons name="checkmark-circle" size={18} color="#25D366" />}
            </TouchableOpacity>
            <TextInput
              style={styles.customTemplateInput}
              value={customTemplate} onChangeText={setCustomTemplate}
              placeholder="Write your custom message here..."
              placeholderTextColor="#9CA3AF" multiline
              onFocus={() => setSelectedTemplate('custom')}
            />
          </View>
        </View>

        {selectedPreset && (
          <View style={styles.previewBox}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 }}>
              <Ionicons name="eye-outline" size={14} color="#25D366" />
              <Text style={{ fontSize: 12, fontWeight: '700', color: '#25D366' }}>Preview Message</Text>
            </View>
            <Text style={styles.previewText}>
              {selectedTemplate === 'custom'
                ? (customTemplate || 'Your custom message will appear here...')
                : selectedPreset.template}
            </Text>
          </View>
        )}

        <TouchableOpacity style={styles.saveBtn} onPress={handleSave}>
          <Ionicons name="save-outline" size={18} color="#FFF" />
          <Text style={styles.saveBtnText}>Save WhatsApp Settings</Text>
        </TouchableOpacity>

        <View style={styles.infoBanner}>
          <Ionicons name="information-circle-outline" size={18} color="#3B82F6" />
          <Text style={styles.infoText}>
            BillForge uses WhatsApp Web/App links to send messages. When sending a bill, it pre-fills the message and opens WhatsApp for you to confirm before sending. For fully automated sending without clicks, integrate with WhatsApp Business API.
          </Text>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F0F4F8' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FFF', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#EAECF0' },
  headerTitle: { fontSize: 17, fontWeight: '700', color: '#1A1F2C' },
  headerSub: { fontSize: 12, color: '#6B7280' },
  waBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#25D366', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  waBadgeText: { color: '#FFF', fontSize: 12, fontWeight: '700' },
  section: { backgroundColor: '#FFF', borderRadius: 14, padding: 16, marginBottom: 16 },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: '#1A1F2C', marginBottom: 4 },
  sectionSub: { fontSize: 12, color: '#6B7280', marginBottom: 14, lineHeight: 18 },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  countryCode: { backgroundColor: '#F3F4F6', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 12 },
  countryCodeText: { fontSize: 14, fontWeight: '600', color: '#374151' },
  inputField: { flex: 1, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, color: '#1A1F2C' },
  testBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#F0FDF4', borderWidth: 1, borderColor: '#22C55E', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 11 },
  testBtnText: { fontSize: 13, fontWeight: '600', color: '#22C55E' },
  settingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#F0F0F0', gap: 12 },
  settingLabel: { fontSize: 14, fontWeight: '600', color: '#1A1F2C' },
  settingDesc: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  templateCard: { backgroundColor: '#F8FAFC', borderWidth: 1.5, borderColor: '#E5E7EB', borderRadius: 10, padding: 12, marginBottom: 10 },
  templateCardActive: { borderColor: '#25D366', backgroundColor: '#F0FDF4' },
  templateTitle: { fontSize: 13, fontWeight: '700', color: '#374151' },
  templatePreview: { fontSize: 12, color: '#6B7280', marginTop: 6, lineHeight: 18 },
  customTemplateInput: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, padding: 10, fontSize: 13, color: '#1A1F2C', minHeight: 80, textAlignVertical: 'top' },
  previewBox: { backgroundColor: '#E7FBE7', borderRadius: 12, padding: 14, marginBottom: 16, borderLeftWidth: 4, borderLeftColor: '#25D366' },
  previewText: { fontSize: 13, color: '#1A1F2C', lineHeight: 20 },
  saveBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#25D366', borderRadius: 12, paddingVertical: 14, marginBottom: 14 },
  saveBtnText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
  infoBanner: { flexDirection: 'row', gap: 10, backgroundColor: '#EFF6FF', borderRadius: 12, padding: 12 },
  infoText: { flex: 1, fontSize: 12, color: '#374151', lineHeight: 18 },
});
